export const CHANNEL_ITEM_CREATE = 'CHANNEL_ITEM_CREATE';
export const CHANNEL_ITEM_DELETE = 'CHANNEL_ITEM_DELETE';
export const CHANNEL_ITEM_UPDATE = 'CHANNEL_ITEM_UPDATE';
export const MESSAGE_CREATE = 'MESSAGE_CREATE';
export const MESSAGE_DELETE = 'MESSAGE_DELETE';
export const MESSAGE_UPDATE = 'MESSAGE_UPDATE';