export const CHANNEL_CREATE = 'CHANNEL_CREATE';
export const CHANNEL_DELETE = 'CHANNEL_DELETE';
export const CHANNEL_UPDATE = 'CHANNEL_UPDATE';
export const START_EDITING_CHANNEL = 'START_EDITING_CHANNEL';
export const CANCEL_EDITING_CHANNEL = 'CANCEL_EDITING_CHANNEL';
export const MESSAGE_CREATE = 'MESSAGE_CREATE';
export const MESSAGE_DELETE = 'MESSAGE_DELETE';
export const MESSAGE_UPDATE = 'MESSAGE_UPDATE';